/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: LocalizedString;
  accentColor?: "yellow" | "green" | "cyan" | "orange" | "purple";
  skills?: Array<string>;
  orderRank?: number;
};

export type LocalizedString = {
  _type: "localizedString";
  es?: string;
  en?: string;
};

export type Timeline = {
  _id: string;
  _type: "timeline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  period?: string;
  role?: LocalizedString;
  organization?: LocalizedString;
  description?: LocalizedText;
  bulletsEs?: Array<string>;
  bulletsEn?: Array<string>;
  type?: "experience" | "education";
  accentColor?: "yellow" | "green" | "cyan" | "orange" | "purple";
  orderRank?: number;
};

export type LocalizedText = {
  _type: "localizedText";
  es?: string;
  en?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  serviceId?: string;
  title?: LocalizedString;
  deliverables?: LocalizedString;
  description?: LocalizedText;
  folderColor?: "yellow" | "green" | "cyan" | "orange" | "purple" | "pink";
  iconName?: "Rocket" | "Sparkles" | "LayoutGrid" | "ShieldCheck";
  orderRank?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: LocalizedString;
  location?: string;
  email?: string;
  whatsappNumber?: string;
  whatsappMessage?: LocalizedString;
  github?: string;
  linkedin?: string;
  statusBadge?: LocalizedString;
  bio?: LocalizedText;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "client_b2b" | "saas_ai" | "labs";
  tag?: LocalizedString;
  folderColor?: "yellow" | "green" | "cyan" | "orange" | "purple" | "pink";
  problem?: LocalizedText;
  solution?: LocalizedText;
  impact?: LocalizedText;
  stack?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  link?: string;
  github?: string;
  confidential?: boolean;
  orderRank?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Metric = {
  _type: "metric";
  value?: string;
  label?: LocalizedString;
  badge?: string;
  color?: "yellow" | "green" | "cyan" | "orange";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SkillCategory
  | LocalizedString
  | Timeline
  | LocalizedText
  | Service
  | SanityImageAssetReference
  | Profile
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | Metric
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../portfolio/src/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0]{    _id,    name,    role,    location,    email,    whatsappNumber,    whatsappMessage,    github,    linkedin,    statusBadge,    bio,    avatar,    metrics[]{      _key,      value,      label,      badge,      color    }  }
export type PROFILE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  role: LocalizedString | null;
  location: string | null;
  email: string | null;
  whatsappNumber: string | null;
  whatsappMessage: LocalizedString | null;
  github: string | null;
  linkedin: string | null;
  statusBadge: LocalizedString | null;
  bio: LocalizedText | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  metrics: Array<{
    _key: string;
    value: string | null;
    label: LocalizedString | null;
    badge: string | null;
    color: "cyan" | "green" | "orange" | "yellow" | null;
  }> | null;
} | null;

// Source: ../portfolio/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank asc, _createdAt desc){    _id,    title,    "slug": slug.current,    category,    tag,    folderColor,    problem,    solution,    impact,    stack,    image,    link,    github,    confidential,    orderRank  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  category: "client_b2b" | "labs" | "saas_ai" | null;
  tag: LocalizedString | null;
  folderColor:
    "cyan" | "green" | "orange" | "pink" | "purple" | "yellow" | null;
  problem: LocalizedText | null;
  solution: LocalizedText | null;
  impact: LocalizedText | null;
  stack: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  link: string | null;
  github: string | null;
  confidential: boolean | null;
  orderRank: number | null;
}>;

// Source: ../portfolio/src/sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(orderRank asc, _createdAt asc){    _id,    serviceId,    title,    deliverables,    description,    folderColor,    iconName,    orderRank  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  serviceId: string | null;
  title: LocalizedString | null;
  deliverables: LocalizedString | null;
  description: LocalizedText | null;
  folderColor:
    "cyan" | "green" | "orange" | "pink" | "purple" | "yellow" | null;
  iconName: "LayoutGrid" | "Rocket" | "ShieldCheck" | "Sparkles" | null;
  orderRank: number | null;
}>;

// Source: ../portfolio/src/sanity/queries.ts
// Variable: TIMELINE_QUERY
// Query: *[_type == "timeline"] | order(orderRank asc, _createdAt desc){    _id,    period,    role,    organization,    description,    bulletsEs,    bulletsEn,    type,    accentColor,    orderRank  }
export type TIMELINE_QUERY_RESULT = Array<{
  _id: string;
  period: string | null;
  role: LocalizedString | null;
  organization: LocalizedString | null;
  description: LocalizedText | null;
  bulletsEs: Array<string> | null;
  bulletsEn: Array<string> | null;
  type: "education" | "experience" | null;
  accentColor: "cyan" | "green" | "orange" | "purple" | "yellow" | null;
  orderRank: number | null;
}>;

// Source: ../portfolio/src/sanity/queries.ts
// Variable: SKILL_CATEGORIES_QUERY
// Query: *[_type == "skillCategory"] | order(orderRank asc, _createdAt asc){    _id,    category,    accentColor,    skills,    orderRank  }
export type SKILL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  category: LocalizedString | null;
  accentColor: "cyan" | "green" | "orange" | "purple" | "yellow" | null;
  skills: Array<string> | null;
  orderRank: number | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "profile"][0]{\n    _id,\n    name,\n    role,\n    location,\n    email,\n    whatsappNumber,\n    whatsappMessage,\n    github,\n    linkedin,\n    statusBadge,\n    bio,\n    avatar,\n    metrics[]{\n      _key,\n      value,\n      label,\n      badge,\n      color\n    }\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(orderRank asc, _createdAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    tag,\n    folderColor,\n    problem,\n    solution,\n    impact,\n    stack,\n    image,\n    link,\n    github,\n    confidential,\n    orderRank\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "service"] | order(orderRank asc, _createdAt asc){\n    _id,\n    serviceId,\n    title,\n    deliverables,\n    description,\n    folderColor,\n    iconName,\n    orderRank\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "timeline"] | order(orderRank asc, _createdAt desc){\n    _id,\n    period,\n    role,\n    organization,\n    description,\n    bulletsEs,\n    bulletsEn,\n    type,\n    accentColor,\n    orderRank\n  }\n': TIMELINE_QUERY_RESULT;
    '\n  *[_type == "skillCategory"] | order(orderRank asc, _createdAt asc){\n    _id,\n    category,\n    accentColor,\n    skills,\n    orderRank\n  }\n': SKILL_CATEGORIES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
